### ISSUE TITLE
Could we move this to the WG?

### ISSUE THREAD

**Issue by erlend-sh** [miller-time/rust-warrior#10]
This game might actually be suitable as a community-developed game, under the custodianship of the [Rust GameDev Working Group](https://github.com/rust-gamedev). Might you be interested in moving it there?

**Comment by miller-time** [comment]
Hi again, Erlend.

We talked a while back about a partnership with the Amethyst org. Sorry I never got back to you. I haven't done a lot of Rust development lately.

I don't see other games within that org. Is this a new idea?

I'm curious what the process is like...

Is there a reason moving would be necessary, versus just linking here?

I still love Rust, and I'd still like to learn more about game development. I think Rust Warrior has potential for helping people learn Rust two-fold: first, by simply playing it you can practice some basics; secondly, you can [contribute](https://github.com/miller-time/rust-warrior/contribute). I'm happy to review PRs if folks submit them, and to give pointers about porting things from Ruby Warrior. 

Separate question for you: I'm curious what it's like to be a member of the WG, and what's the process for applying? The reason I ask is that perhaps joining the WG and talking about Rust Warrior in/around the WG would be a good way to get community involvement?
